exports.auth = require('./auth.controller')
exports.option = require('./option.controller')
exports.qiniu = require('./qiniu.controller')
exports.tag = require('./tag.controller')
exports.article = require('./article.controller')
exports.like = require('./like.controller')
exports.comment = require('./comment.controller')
